name: Deploy
# on:
#   push:
#     branches:
#       - master
#   workflow_dispatch:
jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    env:
      REGION: ${{ vars.GCP_REGION }}
      PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      REPOSITORY: ${{ vars.GCP_REPOSITORY }}
      IMAGE_NAME: ${{ vars.GCP_IMAGE_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}
      - name: Configure Docker to use Google Cloud credentials
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet
      - name: Build and push the Docker image
        run: |
          docker build \
            -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} \
            . \
            --push
